site_name: LPP
use_directory_urls: false

nav:
- 'Teoría':
   - 'Descripción de la asignatura': 'teoria/tema00-descripcion-asignatura/tema00-descripcion-asignatura.md'
   - 'Tema 1: Historia de los lenguajes de programación': 'teoria/tema01-historia-lenguajes-programacion/tema01-historia-lenguajes-programacion.md'
   - 'Tema 2: Programación funcional': 'teoria/tema02-programacion-funcional/tema02-programacion-funcional.md'
#   - 'Tema 3: Procedimientos recursivos': 'teoria/tema03-procedimientos-recursivos/tema03-procedimientos-recursivos.md'
#   - 'Tema 4: Estructuras recursivas': 'teoria/tema04-estructuras-recursivas/tema04-estructuras-recursivas.md'
#   - 'Tema 5: Programación funcional con Swift': 'teoria/tema05-programacion-funcional-swift/tema05-programacion-funcional-swift.md'
#   - 'Tema 6: Programación OO con Swift': 'teoria/tema06-programacion-orientada-objetos-swift/tema06-programacion-orientada-objetos-swift.md'
- 'Seminarios':
   - 'Seminario de Scheme': 'seminarios/seminario1-scheme/seminario1-scheme.md'
#   - 'Seminario de Swift': 'seminarios/seminario2-swift/seminario2-swift.md'
# - 'Prácticas':
#   - 'Práctica 1': 'practicas/practica01/practica01.md'
#   - 'Práctica 2': 'practicas/practica02/practica02.md'
#   - 'Práctica 3': 'practicas/practica03/practica03.md'
#   - 'Práctica 4': 'practicas/practica04/practica04.md'
#   - 'Práctica 5': 'practicas/practica05/practica05.md'
#   - 'Práctica 6': 'practicas/practica06/practica06.md'
#   - 'Práctica 7': 'practicas/practica07/practica07.md'
#   - 'Práctica 8': 'practicas/practica08/practica08.md'
#   - 'Práctica 9': 'practicas/practica09/practica09.md'
#   - 'Práctica 10': 'practicas/practica10/practica10.md'
#   - 'Práctica 11': 'practicas/practica11/practica11.md'

theme:
    language: es
    name: 'material'
    palette:
        primary: 'Teal'
        accent: 'Teal'
    font:
        text: 'Merriweather'
        code: 'Roboto Mono'
    logo: 'imagenes/logo.png'

markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
    - footnotes
    - meta
    - sane_lists
    - toc:
       permalink: true
       toc_depth: 3
    - pymdownx.superfences
